[project]
name = "plantgraph3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "biokb_ipni @ git+https://github.com/biokb/biokb_ipni.git",
    "biokb_taxtree @ git+https://github.com/biokb/biokb_taxtree.git",
    "biokb_wcvp @ git+https://github.com/biokb/biokb_wcvp.git",
    "biokb_wfo @ git+https://github.com/biokb/biokb_wfo.git",
    "biokb-brenda @ git+https://github.com/biokb/biokb_brenda.git",
    "biokb_coconut @ git+https://github.com/biokb/biokb_coconut.git",
    "biokb_chebi @ git+https://github.com/biokb/biokb_chebi.git",
    "sqlalchemy>=2.0.46",
    "pandas>=3.0.0",
    "neo4j>=6.1.0",
]

[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-jupyter>=0.24.1",
    "mkdocs-material>=9.7.1",
    "mkdocstrings[python]>=1.0.3",
]
tests = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]

